name: build and push

on:
  push:
    branches:
      - master

jobs:
  main:
    name: pull and push
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: build and push
      uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile
        repository: jonyhy/custom-mongo-tools
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true
        tags: latest
